class BackendStoreKey {
  final Type _type;
  final Object _key;

  BackendStoreKey(this._type, this._key);

  /// NOTE: This method is generated by WebStorm
  @override
  int get hashCode => _type.hashCode ^ _key.hashCode;

  Object get key => _key;

  Type get type => _type;

  /// NOTE: This method is generated by WebStorm
  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is BackendStoreKey && runtimeType == other.runtimeType && _type == other._type && _key == other._key;
  }
}
